# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltexamapp', '0002_auto_20161118_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='users',
        ),
    ]
