# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltexamapp', '0003_auto_20161118_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='users',
            new_name='user',
        ),
    ]
