# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltexamapp', '0006_auto_20161118_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(to='beltexamapp.User'),
        ),
    ]
